# Generated by Django 5.0.1 on 2024-03-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
